accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.models import User

app_name = 'accounts'

urlpatterns = [
    #path('', views.signup_view, name="account-main"),
    path('<str:username>', views.account, name="account"),
    path('login/', views.login_view, name="login"),
    path('client_signup/', views.client_signup, name="signup"),
    path('staff_signup/', views.staff_signup, name="staff_signup"),
    path('logout/', views.logout_view, name="logout"),
    path('update/', views.account_update, name="account_update")

]

dokkaebirepair/urls.py
from django.contrib import admin
from django.urls import path, include
from dokkaebirepair import views
from repairtracker import views as repairtrack_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name="admin_panel"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('accounts.urls')),
    path('repairtracker/', include('repairtracker.urls')),
    path('', views.home, name="home"),
    #path('blog/', include('drblog.urls')),
    #path('about/', views.about, name="about"),
    #path('services/', views.services, name="services"),
    #path('contact/', include('contact.urls')),
    path('search/', repairtrack_views.repairsearch),
    

]

urlpatterns += i18n_patterns(

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repairtracker/urls.py
from django.urls import path
from repairtracker import views
#from .views import print_ticket

app_name = 'repairtracker'

urlpatterns = [
    path('', views.repairdashboard, name="repair-dashboard"),
    path('repairlist', views.repairtracker, name="repair-list"),
    path('create', views.repaircreate, name="repair-create"),
    path('<str:idCase>/ticket', views.ticket_ingreso, name="view-ticket"),
    path('<str:idCase>/<str:idPic>/delete', views.delete_repair_image, name="delete-repair-image"),
    path('<str:idCase>/delete', views.repairdelete, name="repair-delete"),

    path('<str:idCase>', views.repairdetail, name="repair-detail"),
    #path('<str:idCase>/statusUpdate', views.update_status, name="status-update"),
    path('<str:idCase>/update', views.repairupdate, name="repair-update")
    
    #path('<str:idCase>', views.search, name="search"),

]

repairtracker/models.py
import os
import uuid
from django.utils.translation import ugettext as _
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone
from accounts.models import Client
from django.contrib.auth.models import User
from django import forms


class Device(models.Model):

    
    DEVICE_TYPE_CHOICES=(
        ('LAP', 'Laptop'),
        ('DESK', 'Desktop'),
        ('PHONE', 'Cellphone/Smartphone'),
        ('TABLET', 'Tablet'),
        ('AIO', 'All-In-One'),
    )

    DEV_POWER_CHOICES=(
        ('ON', 'Encendido'),
        ('OFF', 'Apagado') 
    )


    DEV_ASSEMBLY_CHOICES=(
        ('ARM', 'Armado'),
        ('DES', 'Desarmado')
    )


    DEV_CHARGECABLE_CHOICES=(
        ('CON', 'Con Cable de Carga'),
        ('SIN', 'Sin Cable de Carga'),
    )

    DEV_CHARGEADAPTER_CHOICES=(
        ('CON', 'Con Adaptador de Carga'),
        ('SIN', 'Sin Adaptador de Carga'),
    )


    DEV_BATTERY_CHOICES=(
        ('CON', 'Con Bateria'),
        ('SIN', 'Sin Bateria')
    )

    DEV_SIM_CHOICES=(
        ('CON', 'Con Tarjeta SIM'),
        ('SIN', 'Sin Tarjeta SIM')
    )

    DEV_CASE_CHOICES=(
        ('CON', 'Con Funda'),
        ('SIN', 'Sin Funda')
    )

    DEV_SDCARD_CHOICES=(
        ('CON', 'Con Memoria'),
        ('SIN', 'Sin Memoria')
    )
    id_device = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, default=None, on_delete=models.CASCADE)
    serialNumber = models.CharField(blank=True, max_length=40)
    devType = models.CharField(max_length=15, blank=True, choices=DEVICE_TYPE_CHOICES, default='Smartphone')
    devBrand = models.CharField(max_length=20)
    devModel = models.CharField(max_length=100, default="")
    
    #password y tipo de password del dispositivo
    passPin = models.CharField(max_length=10, blank=True, null=True)
    passWord = models.CharField(max_length=100, blank=True, null=True)
    passPatt = models.CharField(max_length=50, blank=True, null=True)

    #condiciones del equipo al recibirlo
    con_devPower=models.CharField(max_length=10, default='OFF', choices=DEV_POWER_CHOICES, blank=False)
    con_devAssembly=models.CharField(max_length=10, default='ARM', choices=DEV_ASSEMBLY_CHOICES, blank=False)
    con_devChargeCable=models.CharField(max_length=10, default='CON', choices=DEV_CHARGECABLE_CHOICES, blank=False)
    con_devChargeAdapter=models.CharField(max_length=10, default='CON', choices=DEV_CHARGEADAPTER_CHOICES, blank=False)
    con_devBattery=models.CharField(max_length=10, default='CON', choices=DEV_BATTERY_CHOICES, blank=False)
    con_devSIM=models.CharField(max_length=10, default='CON', choices=DEV_SIM_CHOICES, blank=False)
    con_devCase=models.CharField(max_length=10, default='CON', choices=DEV_CASE_CHOICES, blank=False)
    con_devSDCard=models.CharField(max_length=10, default='CON', choices=DEV_SDCARD_CHOICES, blank=False)

# Create your models here.
class Repair(models.Model):

    #make instance id user id instead
    def get_image_path(self, instance, filename):
        return os.path.join('/media/', instance.idCase, filename)

    STATUSES=(
        ('NA', 'N/A'),
        ('COT', 'Cotizacion'),
        ('PREP', 'Reparacion'),
        ('REP', 'Reparado. Listo para Entrega'),
        ('ENT', 'Entregado/Fuera de Tienda'),
        ('DES', 'Reparacion/Cotizacion no Realizada'),
    )

    idCase = models.UUIDField(default=uuid.uuid4, editable=False, blank=False)
    ##slug = models.SlugField()
    device = models.ForeignKey(Device, default=None, on_delete=models.CASCADE)
    startDate = models.DateTimeField(auto_now_add=True)
    lastModified = models.DateTimeField(auto_now=True)
    probDescription = models.TextField()
    technician = models.ForeignKey('accounts.Usuario', on_delete=models.CASCADE, null=True, blank=True)
    repairDetail = models.TextField(blank=True)
    repairCost = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0.00)], blank=True, default=0.00)
    payment = models.OneToOneField('repairtracker.Payment', default=None, on_delete=models.CASCADE)
    


    def __str__(self):
        return str(self.idCase)


    def snippet(self):
        return str(self.probDescription[:50])

    @classmethod
    def create(cls, idCase):
        repair = cls(idCase=idCase)
        return repair



class Cellphone(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE, blank=True)
    imei = models.CharField(max_length=30, null=True, blank=True)
    cel_number = models.CharField(max_length=30, null=True, blank=True)
    provider = models.CharField(max_length=30, null=True, blank=True)
    

class Images(models.Model):
    repair = models.ForeignKey(Repair, default=None, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, verbose_name='Image')

'''
class Complaint(models.Model):
    repair = models.ForeignKey(Repair, default=None, on_delete=models.CASCADE)
    description = models.CharField(max_length=300, null=True)
'''


class Repair_status(models.Model):
    STATUSES=(
        ('NA', 'N/A'),
        ('COT', 'Cotizacion'),
        ('PREP', 'Reparacion'),
        ('REP', 'Reparado. Listo para Entrega'),
        ('ENT', 'Entregado/Fuera de Tienda'),
        ('DES', 'Reparacion/Cotizacion no Realizada'),
    )
    repair = models.ForeignKey(Repair, default=None, on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)
    repairStatus = models.CharField(max_length=5, choices=STATUSES, default = 'PREP')
    statusDetail = models.CharField(max_length = 100, null=True)
    


class Payment(models.Model):
    P_STATUSES =(
        ('PEN', 'Pendiente'),
        ('DONE', 'Pagado'),
        ('DISC', 'Descartado')
    )

    P_TYPES = (
        ('CARD', 'Tarjeta'),
        ('CASH', 'Efectivo')
    )

    payment_id = models.AutoField(primary_key=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_closed = models.DateTimeField()
    payment_type = models.CharField(max_length=5, choices = P_TYPES, default='CASH')
    payment_status = models.CharField(max_length=5, choices= P_STATUSES, default='PEN')
    total_cost = models.DecimalField(max_digits=15, decimal_places=2, null=True)
    received = models.DecimalField(max_digits=15, decimal_places=2, null=True)
    change = models.DecimalField(max_digits=15, decimal_places=2, null=True)

class Concept(models.Model):
    payment = models.ForeignKey(Payment, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length = 30, null=True)
    cost = models.DecimalField(max_digits=15, decimal_places=2, null=True)
    quantity = models.SmallIntegerField(default=1)


    


    

repairtracker/forms.py
from django import forms
from repairtracker.models import Repair, Images, Device, Repair_status, Cellphone

class CreateRepair(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Repair
        fields = ['technician', 'device' , 'probDescription', 'repairCost']
        labels = {
            'technician': 'Tecnico',
            'device': 'Dispositivo',
            'probDescription': 'Problema',
            'repairCost': 'Costo total de Reparacion',
        }

        widgets = {
            'probDescription': forms.Textarea(attrs={'onkeyup':'auto_grow(this)', 'rows':'2'}),
            'repairCost': forms.TextInput(attrs={'placeholder': '0.00'}),
        }

class CreateDevice(forms.ModelForm):
    required_css_class = 'required'
    def clean(self):
        serialNumber = self.cleaned_data.get('serialNumber')
        imeiNumber = self.cleaned_data.get('imeiNumber')

        if not serialNumber and not imeiNumber:
            msg = forms.ValidationError("No. Serial o IMEI requerido. No dejar ambos en blanco!")
            self.add_error('serialNumber', msg)
            self.add_error('imeiNumber', msg)
            raise msg
    
    class Meta:

        DEV_POWER_CHOICES=(
            ('ON', 'Encendido'),
            ('OFF', 'Apagado') 
        )


        DEV_ASSEMBLY_CHOICES=(
            ('ARM', 'Armado'),
            ('DES', 'Desarmado')
        )


        DEV_CHARGECABLE_CHOICES=(
            ('CON', 'Con Cable de Carga'),
            ('SIN', 'Sin Cable de Carga'),
        )

        DEV_CHARGEADAPTER_CHOICES=(
            ('CON', 'Con Adaptador de Carga'),
            ('SIN', 'Sin Adaptador de Carga'),
        )


        DEV_BATTERY_CHOICES=(
            ('CON', 'Con Bateria'),
            ('SIN', 'Sin Bateria')
        )

        DEV_SIM_CHOICES=(
            ('CON', 'Con Tarjeta SIM'),
            ('SIN', 'Sin Tarjeta SIM')
        )

        DEV_CASE_CHOICES=(
            ('CON', 'Con Funda'),
            ('SIN', 'Sin Funda')
        )

        DEV_SDCARD_CHOICES=(
            ('CON', 'Con Memoria'),
            ('SIN', 'Sin Memoria')
        )
        model=Device
        fields = [
            'serialNumber',
            'client',
            'devType',
            'devBrand',
            'devModel',
            'passPin',
            'passWord',
            'passPatt',
            'con_devPower',
            'con_devAssembly',
            'con_devChargeCable',
            'con_devChargeAdapter',
            'con_devSIM',
            'con_devCase',
            'con_devSDCard',
            'con_devBattery',
        ]
        labels = {
            'serialNumber': 'No. Serial',
            'client':'Cliente',
            'devType': 'Tipo',
            'devBrand': 'Marca',
            'devModel': 'Modelo',
            'passPin': 'PIN',
            'passWord': 'Password',
            'passPatt': 'Patron',
            'con_devPower': '',
            'con_devAssembly': '',
            'con_devChargeCable': '',
            'con_devChargeAdapter': '',
            'con_devSIM': '',
            'con_devCase': '',
            'con_devSDCard': '',
            'con_devBattery': '',
        }
        widgets = {
            'con_devPower': forms.RadioSelect(attrs={'onClick':'devConditionCheck_power();'},choices=DEV_POWER_CHOICES),
            'con_devAssembly': forms.RadioSelect(attrs={'onClick':'devConditionCheck_assembly();'},choices=DEV_ASSEMBLY_CHOICES),
            'con_devChargeCable': forms.RadioSelect(attrs={},choices=DEV_CHARGECABLE_CHOICES),
            'con_devChargeAdapter': forms.RadioSelect(attrs={},choices=DEV_CHARGEADAPTER_CHOICES),
            'con_devSIM': forms.RadioSelect(attrs={},choices=DEV_SIM_CHOICES),
            'con_devCase': forms.RadioSelect(attrs={},choices=DEV_CASE_CHOICES),
            'con_devSDCard': forms.RadioSelect(attrs={},choices=DEV_SDCARD_CHOICES),
            'con_devBattery': forms.RadioSelect(attrs={'onClick':'devConditionCheck_battery();'},choices=DEV_BATTERY_CHOICES),
            'passPin': forms.PasswordInput(),
            'passWord': forms.PasswordInput(),
        }
        
class CreateCellphone(forms.ModelForm):
    class Meta:
        model = Cellphone
        fields = ['cel_number', 'imei', 'provider']
        labels = {
            'cel_number' : 'Numero Celular',
            'imei' : 'Numero IMEI',
            'provider': 'Compañia Telefonica'
        }


class UpdateRepair(forms.ModelForm):

    
    class Meta:
        model = Repair
        fields = ['technician', 'device' , 'probDescription', 'repairCost']
        labels = {
            'technician': 'Tecnico',
            'device': 'Dispositivo',
            'probDescription': 'Problema',
            'repairCost': 'Costo total de Reparacion',
        }

        widgets = {
            'probDescription': forms.Textarea(attrs={'onkeyup':'auto_grow(this)', 'rows':'2'}),
            'repairCost': forms.TextInput(attrs={'placeholder': '0.00'}),
        }


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Imagen')
    class Meta:
        model = Images
        fields = ('image', )

class CreateStatus(forms.ModelForm):
    class Meta:
        model=Repair_status
        fields = ['repair','repairStatus']
        labels = {
            'repairStatus': 'Estado de Reparacion',
            'repair': 'Reparacion',
            
        }


class UpdateStatus(forms.ModelForm):
    class Meta:
        model = Repair_status
        fields = ['repair','repairStatus']
        labels = {
            'repairStatus': 'Estado de Reparacion',
            'repair': 'Reparacion',
            
        }

repairtracker/templates/repairtracker/repairdetail.html
{% extends 'base.html' %}

{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Detalle de Reparación
{% endblock %}

{% block styles %}
<link href="{% static 'repairdetail_styles.css' %}" rel="stylesheet">
<link href="{% static 'patternlock/patternlock.css' %}" rel="stylesheet">
<link href="{% static 'patternlock/patternlock-wdirection.css' %}" rel="stylesheet">

{% endblock %}


{% block content %}

{% if messages %}
<div class="alert alert-success alert-dismissible fade show align-self-center" role="alert">
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

<h1>Detalle de Reparación</h1>
<h3>Folio: {{ repair.id }}</h3>
<div class="repair-detail">
  <div class="repair">
    <hr>
    </hr>
    <h3>Información de Contacto</h3>

    <table class="table table-bordered" cellpadding="10">
      <tr>
        <td>Nombre Propietario</td>
        <td>{{ repair.ownerName }}</td>
      </tr>
      <tr>
        <td>Telefono</td>
        <td>{{ repair.phoneNumber }}</td>
      </tr>
      <tr>
        <td>Correo Electronico</td>
        <td>{{ repair.userEmail }}</td>
      </tr>
      <tr>
        <td>Dispositivo recibido por</td>
        <td>{{ repair.createdBy.first_name }} {{ repair.createdBy.last_name }}</td>
      </tr>
    </table>
    <br />
    <h3>Información de Dispositivo</h3>
    <table class="table table-bordered" cellpadding="10">
      {% if repair.serialNumber %}
      <tr>
        <td>No. Serial</td>
        <td>{{ repair.serialNumber }}</td>
      </tr>
      {% endif %}
      {% if repair.imeiNumber %}
      <tr>
        <td>No. IMEI</td>
        <td>{{ repair.imeiNumber }}</td>
      </tr>
      {% endif %}
      <tr>
        <td>Tipo Dispositivo</td>
        <td>{{ repair.get_devType_display }}</td>
      </tr>
      <tr>
        <td>Marca</td>
        <td>{{ repair.devBrand }}</td>
      </tr>
      <tr>
        <td>Modelo</td>
        <td>{{ repair.devModel }}</td>
      </tr>
      <tr>
        {% if repair.passWord %}
        <td>Password</td>
        <td> {{ repair.passWord }}</td>
        {% elif repair.passPin and repair.passPatt %}
        <td>PassPin</td>
        <td>{{repair.passPin}}</td>
      <tr>
        <td>Patron</td>
        <td>
          <div id="patternHolder2">

          </div>
          Orden de Puntos del Patron: {{repair.passPatt}}
      </tr>
      </td>
      {% elif repair.passPatt %}
      <td>Patron</td>
      <td>
        <div id="patternHolder"></div>
      </td>
      {% elif repair.passPin %}
      <td>PassPin</td>
      <td>{{repair.passPin}}</td>
      {% else %}
      <td>Password</td>
      <td>Sin Contraseña</td>
      {% endif %}
      </tr>
      <tr>
        <td>Inicio Reparación</td>
        <td>{{ repair.startDate }}</td>
      </tr>
      <tr>
        <td>Descripción Problema</td>
        <td>{{ repair.probDescription }}</td>
      </tr>
      {% if repair.repairStatus == "ENT" %}
      <tr class="table-info">
        {% elif repair.repairStatus == "COT" %}
      <tr class="table-warning">
        {% elif repair.repairStatus == "PREP"%}
      <tr class="table-warning2">
        {% elif repair.repairStatus == "REP" %}
      <tr class="table-success">
        {% elif repair.repairStatus == "DES" %}
      <tr class="table-danger">
        {% endif %}
        <td>Estado</td>
        <!---<td>{{ repair.get_repairStatus_display }}</td>-->
        <td>
          <form class="site-form" name="form" action="{% url 'repairtracker:repair-detail' repair.idCase %}" method="POST"
            onChange="form.submit();">
            {% csrf_token %}
            <div class="form-group">


              <div class="form-group bmd-form-group is-filled">

                <div class=" ">
                  <select name="repairStatus" class=" form-control" id="id_repairStatus" autocomplete="off">
                    <option selected>{{repair.get_repairStatus_display}}</option>

                    <option value="COT">Cotizacion</option>

                    <option value="PREP">Reparacion</option>

                    <option value="REP">Reparado. Listo para Entrega</option>

                    <option value="ENT">Entregado/Fuera de Tienda</option>

                    <option value="DES">Reparacion/Cotizacion no Realizada</option>

                  </select>

                </div>

              </div>

            </div>

          </form>
        </td>
      </tr>
      <tr class="table-primary">
        <td>Detalle Estado</td>
        <td>{{ repair.repairDetail }}</td>
      </tr>
      <tr>
        <td>Costo Total</td>
        <td>${{ repair.repairCost }}</td>
      </tr>
      <tr>
        <td>Imagenes</td>
        <td>
          <div class="row">
            {% for image in images %}
            {% if image.image %}
            <div class="card">
              <div class="card-body">
                <div class="img-container">
                  <a href="{{ image.image.url }}"><img src="{{ image.image.url }}" height="150" width="150" class="image" /></a>
                  <div class="overlay">
                    <a href="{{ image.image.url }}" class="btn btn-primary btn-raised" role="button" target="_blank">Ver</a>
                    <a href="{% url 'repairtracker:delete-repair-image' repair.idCase image.id %}" class="btn btn-danger btn-raised"
                      role="button">Borrar</a>
                  </div>
                </div>

              </div>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </td>
      </tr>
    </table>

    <div class="card">
      <div class="card-header">
        Condiciones del Equipo al Recibirse
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm">
            {{ repair.get_con_devPower_display }}
          </div>
          <div class="col-sm">
            {{ repair.get_con_devAssembly_display }}
          </div>
          <div class="col-sm">
            {{ repair.get_con_devChargeCable_display }}
          </div>
          <div class="col-sm">
            {{ repair.get_con_devChargeAdapter_display }}
          </div>
          <div class="col-sm">
            {{ repair.get_con_devSIM_display }}
          </div>
          <div class="col-sm">
            {{ repair.get_con_devCase_display }}
          </div>
          <div class="col-sm">
            {{ repair.get_con_devSDCard_display }}
          </div>
          <div class="col-sm">
            {{ repair.get_con_devBattery_display }}
          </div>
        </div>

      </div>
    </div>
    <br />
    {% if user.is_superuser or user.is_staff %}

    {% if user.is_superuser %}
    <a class="btn btn-warning" href="{% url 'repairtracker:repair-update' repair.idCase %}" role="button">Actualizar</a>
    {% endif %}
    <a href="{% url 'repairtracker:view-ticket' repair.idCase %}" class="btn btn-primary btn-raised">Ver Nota de
      Ingreso</a>

    {% if user.is_superuser%}
    <button class="btn btn-danger btn-raised" data-toggle="modal" data-target="#deleteModal">Borrar</button>

  </div>




  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Borrar Registro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Seguro que desea borrar el Registro?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          <a class="btn btn-danger btn-raised" href="{% url 'repairtracker:repair-delete' repair.idCase %}" role="button">Borrar</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  {% endif %}


</div>
</div>




{% endblock %}

{% block scripts %}
<script src="{% static 'patternlock/patternlock.js' %}"></script>
<script>
  var lock = new PatternLock('#patternHolder2', { enableSetPattern: true });
  lock.setPattern(123578);
</script>



<script>
  var sizeTheOverlays = function () {
    $(".overlay").resize().each(function () {
      var h = $(this).parent().outerHeight();
      var w = $(this).parent().outerWidth();
      $(this).css("height", h);
      $(this).css("width", w);
    });
  };

  sizeTheOverlays();


  var width = $(window).width();
  $(window).resize(function () {
    if ($(this).width() != width) {
      width = $(this).width();
      sizeTheOverlays();
    }
  });
</script>


{% endblock %}

repairtracker/templates/repairtracker/repairsearch.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block subtitle %}
  Buscar Reparación
{% endblock %}

{% block styles %}
  <link href="{% static 'repairsearch_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% if messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   <ul>
       {% for message in messages %}
       <li>{{ message }}</li>
       {% endfor %}
   </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<h1>Buscar Reparación</h1>
<label>No. Rastreo: </label>
    <form action="{% url 'repairtracker:search' %}" method="GET">
        <input class="form-control" type="text" id="search_textbox" name="q" required>
        <input class="btn btn-primary" type="submit" id="search_button" value="Buscar">
    </form>

{% endblock %}

repairtracker/templates/repairtracker/ticket_venta.html
{% load static from staticfiles %}
{% load staticencoder %}
 <html>
     <head>
         <title>Ticket de Venta</title>

     </head>
     <body>
         <div class='wrapper'>
             <div class='header'>
                 <div class="row">

                 <div class="col-sm">
                    <img src="{% static 'imgs/dokkaebi.png' %}" alt="Company Logo">
                </div>
                <div class="col">
                    <p class='title'>Ticket de Venta</p>
                    <p class='folio'>Folio: <span id='folioventa'> No. {{ repair.id }}</span></p>
                </div>

            </div>
                 
             </div>
        </div>
        
            <div class='details' id="cuerpo">
                Propietario: {{ repair.ownerName }} <br/>
                Tel: {{ repair.phoneNumber }} <br/>

                {% if repair.userEmail %}
                Correo Electrónico: {{ repair.userEmail }} <br/>
                {% endif %}
                
                Fecha: {{ repair.startDate }}

                <hr class='hrItem' />
                <table class="table table-bordered" cellpadding="10">
                        <tr>
                            <td>Tipo Dispositivo</td>
                            <td>{{ repair.get_devType_display }}</td>

                        </tr>
                        <tr>
                            <td>Marca</td>
                            <td>{{ repair.devBrand }}</td>

                        </tr>
                        <tr>
                            <td>Modelo</td>
                            <td>{{ repair.devModel}}</td>
                        </tr>
                        <tr>
                            <td>No. Serial</td>
                            <td>{{ repair.serialNumber }}</td>
                        </tr>
                        <tr>
                          <td>Descripción del Problema</td>
                          <td>{{ repair.probDescription }}</td>
                        </tr>
                        <tr>
                            <td>Condiciones del Equipo al Recibirse</td>
                            <td>
                                <ul>
                                    <li>{{ repair.get_con_devPower_display }}</li>
                                    <li>{{ repair.get_con_devAssembly_display }}</li>
                                    <li>{{ repair.get_con_devCharger_display }}</li>
                                    <li>{{ repair.get_con_devBattery_display }}</li>
                                </ul>
                            </td>
                        </tr>

                        </table>
  
            </div>
        
        <div id="firma">
            <p id="firma-campo">____________________________________________</p>
            <p id="firma-label">ACEPTO Firma del Cliente</p>
        </div>
     </body>
 </html>