accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.models import User

app_name = 'accounts'

urlpatterns = [
    #path('', views.signup_view, name="account-main"),
    path('<str:username>', views.account, name="account"),
    path('login/', views.login_view, name="login"),
    path('client_signup/', views.client_signup, name="signup"),
    path('staff_signup/', views.staff_signup, name="staff_signup"),
    path('logout/', views.logout_view, name="logout"),
    path('update/', views.account_update, name="account_update")

]

dokkaebirepair/urls.py
from django.contrib import admin
from django.urls import path, include
from dokkaebirepair import views
from repairtracker import views as repairtrack_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name="admin_panel"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('accounts.urls')),
    path('repairtracker/', include('repairtracker.urls')),
    path('', views.home, name="home"),
    #path('blog/', include('drblog.urls')),
    #path('about/', views.about, name="about"),
    #path('services/', views.services, name="services"),
    #path('contact/', include('contact.urls')),
    path('search/', repairtrack_views.repairsearch),
    

]

urlpatterns += i18n_patterns(

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from accounts.models import Usuario


class Signup_UserCreationForm(UserCreationForm):

    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = Usuario.objects.filter(username=username)
        if r.count():
            raise ValidationError("Nombre de usuario no disponible.")
        return username
    
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        widgets = {

        }

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = Usuario.objects.filter(email=email)
        if r.count():
            raise ValidationError("Cuenta con este correo ya existente.")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Contraseñas no coinciden.")

        return password1

    def save(self, commit=True):
        user = super(Signup_UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if user.first_name: 
            user.first_name = self.cleaned_data.get('first_name')
        if user.last_name:
            user.last_name = self.cleaned_data.get('last_name')
        if user.email :
            user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        return user

        

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'username': 'Nombre de Usuario',
            'email': 'Correo Electronico',
            'first_name': 'Nombre',
            'last_name': 'Apellido'
        }


#class CollaboratorProfileForm(forms.ModelForm):

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import Signup_UserCreationForm, UserProfileForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import Permission, Group
from accounts.models import Usuario, Employee, Client, Address
from django.template import RequestContext
from dokkaebirepair.decorators import client_required, employee_required, permissions_required
#from django.views.decorators.csrf import csrf_exempt
# Create your views here.
#@csrf_exempt

@login_required(login_url='accounts:login')
@permission_required('can_add_usuario')
#signup para tecnicos/empleados
def staff_signup(request):
    role_title = 'Employee'
    if request.method=='POST':
        form = Signup_UserCreationForm(request.POST)
        if form.is_valid():
            #permission = Permission.objects.get(name='is_staff')
            
            user = form.save(commit=False)
            user.role = 2

            #automatically adding perms
            
            user.save()
            if user.role == 2:
                Employee.objects.create(profile=user, id_employee = user.user_id)
                group = Group.objects.get(name='employees')
                user.groups.add(group)
            #user.set_permissions.add(permission)
            #login(request, user)
            messages.success(request, 'Cuenta creada!')
            return redirect('home') #HttpResponse('Success!')

    else:
        
        form = Signup_UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form, 'role_title':role_title})

def client_signup(request):
    role_title = 'Client'
    if request.method == 'POST':
        form = Signup_UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.role == 1
            user.save()
            if user.role == 1:
                Client.objects.create(profile=user, id_client = user.user_id)
                group = Group.objects.get(name='clients')
                user.groups.add(group)
            login(request, user)
            messages.success(request, 'Cuenta de cliente creada!')
            return redirect('home')
    else:
        form = Signup_UserCreationForm()
    
    return render(request, 'accounts/signup.html', {'form': form, 'role_title':role_title})

#@permission_required('accounts.is_collab', raise_exception=True)
#def staffsignup_view(request):
#    if request.method=='POST':
#        form = Signup_UserCreationForm(request.POST)
#        if form.is_valid():
#            permission = Permission.objects.get(name='is_collab')
#            user = form.save()
#            user.set_permssions.add(permission)
#            login(request, user)
#            messages.success(request, 'Account created!')
#            return redirect('accounts:staff_signup') #HttpResponse('Success!')
#    else:
#        form = Signup_UserCreationForm()

#    return render(request, 'accounts/staffsignup.html', {'form': form})

def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in User
            user = form.get_user()
            if user.is_active == True:
                login(request, user)
            else:
                messages.error('Usuario bloqueado. Contacte a soporte técnico.')
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('accounts:account', request.user.username)
        else:
                messages.error(request, "Nombre de Usuario o contraseña incorrecta. NOTA: Nombre de Usuario debe ser en MINUSCULAS")
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})

@login_required(login_url='accounts:login')
@permission_required('can_view_usuario')
def account(request, username):
    user = Usuario.objects.get(username=username)
    form = UserProfileForm(instance=user)
    return render(request,'accounts/account.html', {'user': user})


@login_required(login_url='accounts:login')
@permission_required('can_change_usuario')
def account_update(request, template_name="accounts/account_form.html"):
    if request.method=="POST":
        form = UserProfileForm(data=request.POST, instance=request.user)
        update = form.save(commit=False)
        update.user = request.user.username
        update.save()
        return redirect('accounts:account', request.user)
    else:
        form = UserProfileForm(instance=request.user)

    return render(request, 'accounts/account_form.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')
    else:
        return HttpResponse('Not a POST request')

accounts/templates/accounts/account.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subheader %}
  Mi Perfil
{% endblock %}

{% block styles %}
  <link href="{% static 'account_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<form action = "." method="POST">
  {% csrf_token %}

  <div class="container">

    
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-body">
                    <div class="card-header mb-4">
                        <div class="d-flex justify-content-start">
                            <div class="image-container">
                                <img src="http://placehold.it/150x150" id="imgProfile" style="width: 150px; height: 150px"
                                    class="img-thumbnail" />
                                <div class="middle">
                                    <input type="button" class="btn btn-secondary" id="btnChangePicture" value="Change" />
                                    <input type="file" style="display: none;" id="profilePicture" name="file" />
                                </div>
                            </div>
                            <div class="userData ml-3">
                                <h2 class="d-block" style="font-size: 1.5rem; font-weight: bold"><a href="javascript:void(0);">{{ user.username }} {{ user.ap_pat }} {{ user.ap_mat}}</a></h2>
                                
                                <h6 class="d-block">Email: {{user.email}} </h6>
                            </div>
                            <div class="ml-auto">
                                <input type="button" class="btn btn-primary d-none" id="btnDiscard" value="Discard Changes" />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <ul class="nav nav-tabs mb-3" id="myTab" role="tablist">
                                <li class="nav-item">
                                  <a class="nav-link active" id="info-tab" data-toggle="tab" href="#basicInfo" role="tab" aria-controls="home" aria-selected="true">Información Básica</a>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-link" id="repairs-tab" data-toggle="tab" href="#repairs" role="tab" aria-controls="profile" aria-selected="false">Mis Reparaciones</a>
                                </li>

                              </ul>
                              <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="basicInfo" role="tabpanel" aria-labelledby="info-tab">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">Nombre: {{ user.first_name }} {{user.last_name}}</li>
                                        <li class="list-group-item">Email: {{ user.email }}</li>
                                        <li class="list-group-item">Telefono: </li>
                                    </ul>

                                </div>
                                <div class="tab-pane fade" id="repairs" role="tabpanel" aria-labelledby="repairs-tab">
                                    <li class="list-group-item">Numero de Reparaciones: </li>
                                    <div class="row m-3">

                                        
                                        <div class="col">
                                            <div class="card bg-primary text-white">
                                                <div class="card-header d-flex justify-content-between">Pendientes <span class="badge badge-light">4</span></div>
                                                <div class="card-body">

                                                </div>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="card bg-warning text-white">
                                                <div class="card-header d-flex justify-content-between">En proceso<span class="badge badge-light">4</span></div>
                                                <div class="card-body">

                                                </div>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="card bg-success text-white">
                                                <div class="card-header d-flex justify-content-between x">Terminadas<span class="badge badge-light">4</span></div>
                                                <div class="card-body">

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
                              </div>
 
                        </div>
                    </div>
                    <a href="{% url 'accounts:account_update' %}" class="btn btn-primary btn-raised" role="button" aria-pressed="true">Actualizar Perfil</a>

                </div>

            </div>
        </div>
    </div>


</div>






</form>

{% endblock %}

accounts/templates/accounts/account_form.html
{% extends 'base.html' %}

{% load bootstrap %}


{% block subtitle %}
  Actualizar Perfil
{% endblock %}

{% block content %}

<form action = "." method="POST">
  {% csrf_token %}
 

  <table>
    {{ form|bootstrap }}
    <tr>
      <td>
        <input class="btn btn-primary btn-raised" type="submit" value="Guardar">
      </td>
    </tr>
  </table>

</form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block subtitle %}
  Iniciar Sesión
{% endblock %}

{% block content %}
<div class="login">

    {% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
       <ul>
           {% for message in messages %}
           <li>{{ message }}</li>
           {% endfor %}
       </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
   {% endif %}

   <h1>Iniciar Sesión</h1>

    <form method="POST" action="{% url 'accounts:login' %}" >
        {% csrf_token %}
        <table>
           {{ form|bootstrap }}
           {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">

            {% endif %}
            <tr>
               <td></td>
               <td><input class="btn btn-success btn-raised" type="submit" name="submit" value="Iniciar Sesión" /></td>
           </tr>
        </table>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block subtitle %}
Crear Cuenta
{% endblock %}

{% block content %}



<div class="signup">


    <h1>Crear Cuenta</h1>
    <h5>{{role_title}}</h5>

    <form method="POST" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        <table>
            <div class="form-group col-md-6 mx-auto">
                {{ form|bootstrap }}
            </div>
            <div class="form-group col-md-6 mx-auto">
                <input type="submit" class="btn btn-success btn-block btn-raised" name="submit" value="Crear" />
            </div>
        </table>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/staffsignup.html
{% extends 'base.html' %}

{% block content %}
<div class="signup">

    {% if messages %}
       <ul>
           {% for message in messages %}
           <li>{{ message }}</li>
           {% endfor %}
       </ul>
   {% endif %}

   <h1>Create Staff Member account</h1>

    <form method="POST" action="{% url 'accounts:signup' %}" >
        {% csrf_token %}
        <table>
           {{ form.as_table }}
            <tr>
               <td></td>
               <td><input type="submit" name="submit" value="Signup" /></td>
           </tr>
        </table>
    </form>
</div>
{% endblock %}