accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.models import User

app_name = 'accounts'

urlpatterns = [
    #path('', views.signup_view, name="account-main"),
    path('<str:username>', views.account, name="account"),
    path('login/', views.login_view, name="login"),
    path('client_signup/', views.client_signup, name="signup"),
    path('staff_signup/', views.staff_signup, name="staff_signup"),
    path('logout/', views.logout_view, name="logout"),
    path('update/', views.account_update, name="account_update")

]

dokkaebirepair/urls.py
from django.contrib import admin
from django.urls import path, include
from dokkaebirepair import views
from repairtracker import views as repairtrack_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name="admin_panel"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('accounts.urls')),
    path('repairtracker/', include('repairtracker.urls')),
    path('', views.home, name="home"),
    #path('blog/', include('drblog.urls')),
    #path('about/', views.about, name="about"),
    #path('services/', views.services, name="services"),
    #path('contact/', include('contact.urls')),
    path('search/', repairtrack_views.repairsearch),
    

]

urlpatterns += i18n_patterns(

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repairtracker/urls.py
from django.urls import path
from repairtracker import views
#from .views import print_ticket

app_name = 'repairtracker'

urlpatterns = [
    path('', views.repairdashboard, name="repair-dashboard"),
    path('repairlist', views.repairtracker, name="repair-list"),
    path('create', views.repaircreate, name="repair-create"),
    path('<str:idCase>/ticket', views.ticket_ingreso, name="view-ticket"),
    path('<str:idCase>/<str:idPic>/delete', views.delete_repair_image, name="delete-repair-image"),
    path('<str:idCase>/delete', views.repairdelete, name="repair-delete"),

    path('<str:idCase>', views.repairdetail, name="repair-detail"),
    #path('<str:idCase>/statusUpdate', views.update_status, name="status-update"),
    path('<str:idCase>/update', views.repairupdate, name="repair-update")
    
    #path('<str:idCase>', views.search, name="search"),

]

templates/base.html
{% load static from staticfiles %}



<!DOCTYPE html>

<html>

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block subtitle %} {% endblock %} - {{ project_name }}</title>

    <!-- Bootstrap core CSS -->
    <!---<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'bootstrap-material-design.min.css' %}">

    {% block headscripts %}

    {% endblock %}
    <!-- Custom styles for this template -->
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <link href="{% static 'sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'md-iconfont/material-icons.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-select/dist/css/bootstrap-select.css' %}" rel="stylesheet">
    
    <style>


      @font-face {
        font-family: 'Material Icons';
        font-style: normal;
        font-weight: 400;
        src: url("{% static 'md-iconfont/MaterialIcons-Regular.eot' %}"); /* For IE6-8 */
        src: local('Material Icons'),
          local('MaterialIcons-Regular'),
          url("{% static 'md-iconfont/MaterialIcons-Regular.woff2' %}") format('woff2'),
          url("{% static 'md-iconfont/MaterialIcons-Regular.woff' %}") format('woff'),
          url("{% static 'md-iconfont/MaterialIcons-Regular.eot' %}") format('truetype');
      }
    </style>
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
    {% block styles %}

    {% endblock %}
  </head>

  <body>
    <div id="wrapper">
    {% include 'sidebar.html' %}
    {% include 'navbar.html' %}


    <!-- Page Content -->
      <div id="page-content-wrapper">
          <div class="container-fluid" id="content">
              {% include 'messages.html' %}

            {% block content %}

            {% endblock %}

          </div>
      </div>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <br/>
    <footer class="" id="footer">
      <div class="container-fluid">
        <div class="row">

        <div class="col">
          <p class="text-center text-white">Copyright &copy; {{ project_name }} {% now "Y" %}</p>
        </div>

        </div>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->

    <script src="{% static '/bootstrap/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'jquery.disableAutoFill.min.js' %}"></script>
    <script src="{% static 'bootstrap-select/dist/js/bootstrap-select.js' %}"
    
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'scripts.js' %}"></script>
    <script src="{% static 'bootstrap-material-design.js' %}"></script>
 
    <script>
      $(document).ready(function() { $('body').bootstrapMaterialDesign(); });
    </script>
    <script>
        $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
      });
    </script>
    <script>
      $('.form-control').disableAutoFill();
    </script>
    <script>
        // Javascript to enable link to tab
        var url = document.location.toString();
        if (url.match('#')) {
        $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
        }
        
        // Change hash for page-reload
         $('.nav-tabs a').on('shown.bs.tab', function (e) {
         window.location.hash = e.target.hash;
         window.scrollTo(0, 0);
         })
    </script>
    <script>
      function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight)+"px";
    }
    </script>

    
    {% block scripts %}

    {% endblock %}
  
  </body>

</html>

templates/messages.html
{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
        {% for field in form %}
        {% for error in field.errors %}



        <li>{{ error|escape }}</li>



        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}

        <li>{{ error|escape }}</li>

        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

{% if messages %}
<div class="alert alert-warning alert-dismissible fade show align-self-center" role="alert">
   <ul>
       {% for message in messages %}
       <li>{{ message }}</li>
       {% endfor %}
   </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

templates/navbar.html
{% load static from staticfiles %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand navbar-dark navbar-fixed-top">
        <div class="container-fluid">
          <a href="#menu-toggle" class="btn btn-primary mr-2" id="menu-toggle" role="button"><span class="navbar-toggler-icon"></span></a>
          <a class="navbar-brand mx-auto" href="{% url 'home' %}"><img src="{% static 'imgs/dokkaebi.png' %}" class="img-fluid" id="brand-logo" alt="dokkaebi logo" style="width: 110px;"></a>
          <div class="container" id="page-title">
            <h6 class="text-light text-center mt-2"></h6>
          </div>

          
         <!-- {% if user.is_superuser %}
         <i class="material-icons">stars</i>
          {% elif is_staff %}
          <i class="material-icons">verified_user</i>
          {% else %}
  
          {% endif %}-->
          
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto mr-2">
  
              {% if user.is_authenticated %}
              <li class="nav-item">
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                  {% csrf_token %}
                  <div class="dropdown">
                    <a id="username-display" class="btn btn-dark dropdown-toggle" role="button" data-toggle="dropdown">Bienvenido, {{ request.user.username }}</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'accounts:account' user.username %}">Mi Perfil</a>
                        <div class="dropdown-divider"></div>
                        <button type="submit" class="dropdown-item">Cerrar Sesión</button>
                    </div>
                  </div>
                </form>
              </li>
  
              {% else %}
              <li class="nav-item">
                <form class="signup-link" action="{% url 'accounts:signup' %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-info btn-raised">Registrarse</button>
                </form>
              </li>
              <li class="nav-item">
                <form class="login-link" action="{% url 'accounts:login' %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-success btn-raised">Iniciar Sesión</button>
                </form>
              </li>
              {% endif %}
  
  
  
            </ul>
          </div>
        </div>
      </nav>

templates/pdfbase.html
{% load static from staticfiles %}
{% load staticencoder %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block pagetitle%}

            {% endblock %}
        </title>
        <link href="{% static 'ticket_styles.css' %}" rel="stylesheet" media="screen, projection">
        <link href="{% static 'ticket_styles_print.css' %}" rel="stylesheet" media="print">
        <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
        
        <style>

            .background{
                background: url("{% static 'imgs/nar-logo-outline.png' base64 %}");
                background-position: center;
                background-size:70%;
                background-repeat: no-repeat;
                
            }

            .content{
                font-family: 'Courier New', Courier, monospace;
            }



            .watermark {
                display: block;
                position: relative;
                
              }
              
              .watermark::after {
                content: "";
               background:url("{% static 'imgs/dokkaebi.png' base64 %}");
                opacity: 0.03;
                top: 0;
                left: 0;
                bottom: 0;
                right: 0;
                position: absolute;
                z-index: 100;   
                background-size:70%;
                background-repeat: no-repeat;
                background-position: center;
              }
              
 
        </style>
    </head>
    <body size="A5" layout="landscape">
        
    <div class="  content " align="center">
        
        <div align="center">
        <div class="row">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                <img src="{% static 'imgs/dokkaebi.png' %}" alt="">
                
            </div>
            <div class="col-sm">
                        <div id="datosFiscales">

                </div>
            </div>
        </div>

        
        </div>
            <div class="watermark">
            {% block content %}
                
            

            {% endblock %}
    </div>


    
</div>
<div align="center" id="print-btn">
    <button class="btn btn-success" id="printPageButton" onClick="window.print();">
            Imprimir
    </button>
</div>
</body>
</html>

templates/sidebar.html
{% load is_active %}
<div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <span>Menu Principal</span>
            </li>

              <li class="nav-item">
                    <a class="dropdown-item" href="{% url 'repairtracker:repair-list' %}"><span class="material-icons sidebar-icon">assignment</span>Lista de Reparaciones </a>
                </li>
                <li class="nav-item">
                <a class="dropdown-item" href="{% url 'repairtracker:repair-create' %}"><span class="material-icons sidebar-icon">note_add</span>Registrar Dispositivo</a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                  <a class="dropdown-item" href="{% url 'accounts:staff_signup' %}"><span class="material-icons sidebar-icon">person_add</span>Registrar Colaborador</a>
                </li>
                {% endif %}
              <div class="dropdown-divider"></div>
                  <li class="nav-item">
                    <a class="dropdown-item {% is_active 'home' %}" href="{% url 'home' %}"><span class="material-icons sidebar-icon">assessment</span>Inicio</a>
                  </li>

              
            
        </ul>
    </div>